name: continuous-integration
on: 
  push: 
jobs: # Jobs composing the workflow, each one will run on a different runner
    Job-Name: # Every job must be named
        # The type of runner executing the job, usually the OS
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v6
          - uses: actions/setup-java@v5
            with:
              distribution: 'temurin' # See 'Supported distributions' for available options
              java-version: '25'
          - name: gradle
            run: ./gradlew build
